(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const 65536)
  (export "constant_1" (func 0))
  (export "constant_2" (func 0))
  (export "constant_3" (func 0))
  (export "constant_4" (func 0))
  (export "constant_5" (func 0))
  (export "constant_6" (func 0))
  (export "constant_7" (func 0))
  (export "constant_8" (func 0))
  (export "constant_9" (func 0))
  (export "constant_10" (func 0))
  (export "constant_11" (func 0)))
