included:
  - App
  - Sources
  - Tests

excluded:
  - "**/.build"
  - "**/Package"

disabled_rules:
  - nesting
  - vertical_parameter_alignment_on_call
  - extension_access_modifier

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

analyzer_rules:
  - capture_variable
  - unused_import
  - unused_declaration

conditional_returns_on_newline:
  if_only: true

private_over_fileprivate:
  validate_extensions: true
  severity: error

force_unwrapping:
  severity: error

line_length:
  warning: 150
  error: 175
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_name:
  allowed_symbols: "_"
  max_length:
    warning: 60
    error: 60

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length:
    warning: 60
    error: 60
  min_length:
    warning: 1

cyclomatic_complexity:
  warning: 20
  error: 30

file_length:
  warning: 1000
  error: 1300

function_body_length:
  warning: 250
  error: 300

custom_rules:
  tca_internal_action_view_calls:
    included: ".*\\+View\\.swift"
    name: "View Action Boundary"
    regex: ".send\\([\\t|\\n|\\s]*\\.(internal|delegate).*[\\t|\\n|\\s]*\\)"
    capture_group: 1
    message: "Only send view actions within a viewstore."
    severity: error

  tca_feature_reducer_actions:
    included: ".*\\+Reducer\\.swift"
    name: "Reducer Boundary"
    regex: "(?<!action|send)\\(\\s*\\.(internal|view)\\s*(\\(.*\\))?\\)"
    capture_group: 1
    message: "Only access delegate actions of embedded features."
    severity: error

  tca_scope_unused_closure_parameter:
    name: "TCA Scope Unused Closure Parameter"
    regex: '\.scope\(\s*state\s*:\s*\{\s*\_'
    message: "Explicitly use closure parameter when scoping store (ensures the right state is being mutated)"
    severity: error

  xctassertnodifference_preferred:
    name: "XCTAssertNoDifference Preferred"
    regex: 'XCTAssertEqual\('
    message: "Use PointFree's XCTAssertNoDifference from CustomDump library when possible"
    severity: warning
    excluded:
      - ".*/WasmInterpreterTests/.*\\.swift"
      - ".*/ModuleClientTests/.*\\.swift"
      - ".*/CoreORMTests/.*\\.swift"
