# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

lane :tests do
    setup_ci if ENV['CI']
    run_tests(
        scheme: "Mochi",
        project: "./App/Mochi.xcodeproj",
        parallel_testing: true,
        code_coverage: true
    )
end

lane :deploy do
    setup_ci if ENV['CI']
    setup
    archive
    sign
    upload
end

private_lane :setup do
    retrieved_version = true
    version = sh("cog", "bump", "-a", log: false, error_callback: -> (result) { retrieved_version = false })

    if !retrieved_version 
        retrieved_version = true
        version = sh("cog", "-v", "get-version", "--fallback", "0.0.1", log: false, error_callback: -> (result) { retrieved_version = false })
    end

    if retrieved_version
        increment_version_number(
            version_number: version,
            xcodeproj: "./App/Mochi.xcodeproj"
        )

        increment_build_number(
            xcodeproj: "./App/Mochi.xcodeproj"
        )
    else
        UI.crash!("Failed to retrieve version number")
    end
end

private_lane :archive do
    build_successful = true
 
    sh(
#        "set -o pipefall &&",
        "xcodebuild", "archive",
        "-project", "../App/Mochi.xcodeproj",
        "-destination", "generic/platform=iOS",
        "-scheme", "Mochi",
        "-archivePath", "../App/Mochi.xcarchive",
        "CODE_SIGNING_REQUIRED=NO",
        "CODE_SIGNING_ALLOWED=NO",
        "CODE_SIGN_IDENTITY=",
        "CODE_SIGN_ENTITLEMENTS=",
        "GCC_OPTIMIZATION_LEVEL=s",
        "SWIFT_OPTIMIZATION_LEVEL=-O",
        "GCC_GENERATE_DEBUGGING_SYMBOLS=YES",
        "DEBUG_INFORMATION_FORMAT=dwarf-with-dsym | xcbeautify",
        error_callback: -> (result) { build_successful = false }
    )

    if !build_successful
        UI.crash!("Failed to compile iOS archive")
    end

    sh("mkdir", "-p", "../App/Payload")
    sh "cd ../App && mv './Mochi.xcarchive/Products/Applications/Mochi.app' './Payload/Mochi.app'"
    sh "cd ../App && zip -r './Mochi (iOS).ipa' './Payload'"
    sh "cd ../App && mv ./Mochi.xcarchive/dSYMs/* './Mochi dSYMS'"
    sh "cd ../App && zip -r 'Mochi (iOS).dSYM.zip' './Mochi dSYMS'"
    sh "cd ../App && rm -rf ./Payload && rm -rf ./Mochi.xcarchive && rm -rf './Mochi dSYMS'"

# Once TestFlight is available, use fastlane's build in
#    build_ios_app(
#        scheme: "Mochi",
#        project: "./App/Mochi.xcodeproj",
#        destination: "generic/platform=iOS",
#        codesigning_identity: "",
#        verbose: true,
#        skip_codesigning: true
#    )
end

# Sign .ipa and .app once on TestFlight
private_lane :sign do
end

private_lane :upload do
    version = lane_context[SharedValues::VERSION_NUMBER]
    build_number = lane_context[SharedValues::BUILD_NUMBER]

    git_commit(
        path: ["./App/Mochi.xcodeproj/project.pbxproj"], 
        message: "chore(version): v#{version} Build #{build_number}",
        skip_git_hooks: true
    )

    # github_release = set_github_release(
    #     repository_name: "Mochi-Team/mochi",
    #     api_token: ENV["GITHUB_TOKEN"],
    #     name: "Release: v#{version} Build #{build_number}",
    #     tag_name: "v#{version}.#{build_number}",
    #     description: (File.read("changelog") rescue "No changelog provided"),
    #     commitish: "dev",
    #     upload_assets: ["Mochi (iOS).ipa", "./App/Mochi (iOS).ipa"]
    # )
end

