# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

lane :deploy do
    setup_ci if ENV['CI']
    archive if setup?
    sign
    upload
end

private_lane :setup? do
    version_successful = true

    newest_version_number = sh("cog", "bump", "-a", error_callback: -> (result) { version_successful = false })
    if !version_successful 
        UI.error "Failed to retrieve version number"
    else
        increment_version_number(
            version_number: newest_version_number,
            xcodeproj: "./App/Mochi.xcodeproj"
        )
    
        increment_build_number(
            xcodeproj: "./App/Mochi.xcodeproj"
        )    
    end
    version_successful
end

private_lane :archive do
    build_successful = true
 
    sh(
#        "set -o pipefall &&",
        "xcodebuild", "archive",
        "-project", "../App/Mochi.xcodeproj",
        "-destination", "generic/platform=iOS",
        "-scheme", "Mochi",
        "-archivePath", "../App/Mochi (iOS).xcarchive",
        "-xcconfig", "../App/MainConfig.xcconfig",
        "CODE_SIGNING_REQUIRED=NO",
        "CODE_SIGNING_ALLOWED=NO",
        "CODE_SIGN_IDENTITY=",
        "CODE_SIGN_ENTITLEMENTS=",
        "GCC_OPTIMIZATION_LEVEL=s",
        "SWIFT_OPTIMIZATION_LEVEL=-O",
        "GCC_GENERATE_DEBUGGING_SYMBOLS=YES",
        "DEBUG_INFORMATION_FORMAT=dwarf-with-dsym | xcbeautify",
        error_callback: -> (result) { build_successful = false }
    )

    if !build_successful
        UI.error "Failed to build for iOS"
        next
    end

# Once TestFlight is available, use fastlane's build in
#    build_ios_app(
#        scheme: "Mochi",
#        project: "./App/Mochi.xcodeproj",
#        destination: "generic/platform=iOS",
#        codesigning_identity: "",
#        verbose: true,
#        skip_codesigning: true
#    )
end

# Sign .ipa and .app once on TestFlight
private_lane :sign do
end

private_lane :upload do
end

